federation_version: =2.10.0-alpha.0
subgraphs:
  listings:
    routing_url: http://localhost # this value is ignored
    schema:
      file: listings.graphql
  reviews:
    schema:
      subgraph_url: https://rt-airlock-subgraphs-reviews.herokuapp.com/
